"""code_chunk_table

Revision ID: 84a52eb72940
Revises: 8cbe5b7316ae
Create Date: 2026-05-27 18:44:21.885158

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "84a52eb72940"
down_revision: str | Sequence[str] | None = "8cbe5b7316ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_chunk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("chunk_type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("parent_name", sa.String(length=255), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("is_async", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "extra_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repo_id"], ["repo.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_chunk_file_id"), "code_chunk", ["file_id"], unique=False)
    op.create_index(
        "ix_code_chunk_file_start", "code_chunk", ["file_id", "start_line"], unique=False
    )
    op.create_index(op.f("ix_code_chunk_repo_id"), "code_chunk", ["repo_id"], unique=False)
    op.create_index(
        "ix_code_chunk_repo_type", "code_chunk", ["repo_id", "chunk_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_code_chunk_repo_type", table_name="code_chunk")
    op.drop_index(op.f("ix_code_chunk_repo_id"), table_name="code_chunk")
    op.drop_index("ix_code_chunk_file_start", table_name="code_chunk")
    op.drop_index(op.f("ix_code_chunk_file_id"), table_name="code_chunk")
    op.drop_table("code_chunk")
    # ### end Alembic commands ###
