"""baseline_repo_and_file_tables

Revision ID: 8cbe5b7316ae
Revises:
Create Date: 2026-05-25 20:06:37.935625

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cbe5b7316ae"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("default_branch", sa.String(length=128), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner", "name", name="uq_repo_owner_name"),
    )
    op.create_index(op.f("ix_repo_name"), "repo", ["name"], unique=False)
    op.create_index(op.f("ix_repo_owner"), "repo", ["owner"], unique=False)
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["repo_id"], ["repo.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "path", name="uq_file_repo_path"),
    )
    op.create_index(op.f("ix_file_repo_id"), "file", ["repo_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_repo_id"), table_name="file")
    op.drop_table("file")
    op.drop_index(op.f("ix_repo_owner"), table_name="repo")
    op.drop_index(op.f("ix_repo_name"), table_name="repo")
    op.drop_table("repo")
    # ### end Alembic commands ###
